# Generated by Django 3.2.5 on 2022-02-28 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Communities', '0006_communityinvitation'),
        ('Chat', '0006_chat_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='community',
        ),
        migrations.CreateModel(
            name='FriendsChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Chat.chat')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatfriend', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatuser', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Chat.chat',),
        ),
        migrations.CreateModel(
            name='CommunityChat',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Chat.chat')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatcommunity', to='Communities.community')),
            ],
            bases=('Chat.chat',),
        ),
    ]
