# Generated by Django 3.2.5 on 2022-02-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_auto_20220228_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='name',
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(default='community', max_length=10),
        ),
        migrations.AddField(
            model_name='communitychat',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='communitychat',
            name='name',
            field=models.CharField(default='Welcome chat', max_length=50),
        ),
    ]
