# Generated by Django 3.2.5 on 2022-02-28 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0009_auto_20220228_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendschat',
            name='friends',
            field=models.ManyToManyField(related_name='chatfriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
