# Generated by Django 3.2.5 on 2022-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_alter_friendschat_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychat',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
