# Generated by Django 3.2.5 on 2022-01-16 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userfriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
