# Generated by Django 3.2.5 on 2022-01-16 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friends', '0002_alter_friends_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
