# Generated by Django 3.2.5 on 2022-01-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0002_alter_community_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
